In [29]:
import csv
import numpy as np

filename = "../Day 4/eurepoc_global_dataset_.csv"

scores = []

with open(filename, "r", encoding="utf-8") as file:
    reader = csv.DictReader(file)

    for row in reader:
        score = row["impact_indicator_score"]

        if score != "Not available" and score != "":
            scores.append(int(score))

arr = np.array(scores[:20])

print(arr)

[ 8  6  6  6  7  7  7  7  6  8  6  6 11 11  6  7  4  6  5  9]


In [11]:
#insepction
print("Array:", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Total elements:",arr.size)
print("Data type:",arr.dtype)

Array: [ 8  6  6  6  7  7  7  7  6  8  6  6 11 11  6  7  4  6  5  9]
Shape: (20,)
Number of dimensions: 1
Total elements: 20
Data type: int64


In [12]:
matrix = arr.reshape(4, 5)

print(matrix)
print("shape:", matrix.shape)

[[ 8  6  6  6  7]
 [ 7  7  7  6  8]
 [ 6  6 11 11  6]
 [ 7  4  6  5  9]]
shape: (4, 5)


In [15]:
print("one value")
print(matrix[1, 2])
print("entire row")
print(matrix[0, :])
print("entire column")
print(matrix[:, 0])
print("multiple rows")
print(matrix[1:3, :])
print("multiple columns")
print(matrix[:, 1:4])
print("smaller section")
print(matrix[1:3, 1:4])

one value
7
entire row
[8 6 6 6 7]
entire column
[8 7 6 7]
multiple rows
[[ 7  7  7  6  8]
 [ 6  6 11 11  6]]
multiple columns
[[ 6  6  6]
 [ 7  7  6]
 [ 6 11 11]
 [ 4  6  5]]
smaller section
[[ 7  7  6]
 [ 6 11 11]]


In [16]:
new_matrix =  matrix + 1
print("original:")
print(matrix)

print("after adding 1:")
print(new_matrix)

original:
[[ 8  6  6  6  7]
 [ 7  7  7  6  8]
 [ 6  6 11 11  6]
 [ 7  4  6  5  9]]
after adding 1:
[[ 9  7  7  7  8]
 [ 8  8  8  7  9]
 [ 7  7 12 12  7]
 [ 8  5  7  6 10]]


In [19]:
matrix1 = np.ones((4,5), dtype=int)
print(matrix1)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [20]:
result = matrix + matrix1
print(result)

[[ 9  7  7  7  8]
 [ 8  8  8  7  9]
 [ 7  7 12 12  7]
 [ 8  5  7  6 10]]


In [21]:
result = matrix - matrix1
print(result)

[[ 7  5  5  5  6]
 [ 6  6  6  5  7]
 [ 5  5 10 10  5]
 [ 6  3  5  4  8]]


In [22]:
print("Total:", matrix.sum())
print("Average:", matrix.mean())
print("Highest:", matrix.max())
print("Lowest:", matrix.min())

Total: 139
Average: 6.95
Highest: 11
Lowest: 4


In [25]:
identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import csv
import numpy as np

filename = "../Day 4/eurepoc_global_dataset_.csv"

scores = []

with open(filename, "r", encoding="utf-8") as file:
    reader = csv.DictReader(file)

    for row in reader:
        score = row["impact_indicator_score"]

        if score != "Not available" and score != "":
            try:
                scores.append(int(score))
            except ValueError:
                pass

#convert numpy array:
arr = np.array(scores)
print("\n======== DATASET INFO ===========")
print("Total valid records:",len(arr))
print("Data type: ", arr.dtype)

if len(arr)> 0:
    print("First 10 scores:", arr[:10})
    print("Last 10 scores:", arr[-10])

#math functions
print("\n========= MATH OP ========")
if len(arr) > 0:
    print("Minimum score:", np.min(arr))
    print("Maximum score:", np.max(arr))
    print("Average score:", np).mean(arr))
    print("Median score:", np.median())
    print("Standard deviation:", np.std())

#sorting
print("\n======= SORTING =======")
sorted_scores = np.sort(arr)

print("Lowesr 10 scores:")
print(sorted_scores[:10])

print("\nHighesr 10 scores:")
print(sorted_scores[-10:])

#classification of threats
print("\n====== THREATS ========")
low = arr[arr < 40]
medium = arr[(arr >= 40)&(arr <= 70)]
high = arr[arr> 70]

print("Low impact:",len(low))
print("Medium impact:", len(medium))
print("High imapct:", len(high))

#percentages
print("\n========= THREAT PERCENTAGE =========")
total = len(arr)
if total > 0:
    low_percentage = (len(low) / total) * 100
    medium_percentage = (len(medium) / total) * 100
    high_percentage = (len(high) / total) *100

    print("Low:" round(low_percentage, 2), "%")
    print("Medium:" round(medium_percentage, 2), "%")
    print("High:" round(high_percentage, 2), "%")

#extreme scores
print("\n======= EXTREME SCORES =======")
very_high = arr[arr >= 90]
very_low = arr[arr <= 10]

print("Scores >= 90:", very_high)
print("Scores <= 10:",very_high)

print("Number of extremely high scores:", len(very_high))
print("Number of extremely low scores:", len(very-low))

#unique scores
print("======== UNIQUE SCORES ==========")
unique_scores = np.unique(arr)

print("Number of unique scores:", len(unique_scores))
print("Unique scores:")
print(unique_scores)

